language: rust

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
    - rust: nightly
    # MSRV
    - rust: 1.31.0

branches:
  only:
    - master
    - staging
    - trying
